# RT configuration file

# NEW_BASELINE SHOULD BE RENAMED TO USER_BASELINE
  NEW_BASELINE: ${STMP}/${USER}/FV3_RT/REGRESSION_TEST
  RUNDIR_ROOT: ${PTMP}/${USER}/FV3_RT/rt_${MAIN_PID}
  RTPWD: ${DISKNM}/NEMSfv3gfs/develop-${BASELINE_DATE}
  INPUTDATA_ROOT: ${DISKNM}/NEMSfv3gfs/input-data-20250507
  INPUTDATA_ROOT_WW3: ${DISKNM}/NEMSfv3gfs/input-data-20250507/WW3_input_data_20250807
  INPUTDATA_LM4: ${DISKNM}/NEMSfv3gfs/input-data-20250507/LM4_input_data