name: Linting Fortran Files

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fortran-linter
      - name: Lint all fortran files
        run: |
          fortran-linter `find . -iregex ".*\.F[0-9]*" -o -iregex ".*\.for"` --syntax-only
